version: "3.9"
services:
  algorithm-nodejs:
    image: node:16.13.1
    working_dir: /app
    volumes:
      - .:/app
      - '/app/node_modules'
    command: sh -c "npm install && npm start --filename=$$FILENAME"
    environment:
      - FILENAME=1